### ISSUE TITLE
GomlNodeのgetComponentメソッドでコンポーネントがない場合のerrorに関して

### ISSUE THREAD

**Issue by case2912** [GrimoireGL/GrimoireJS#430]
意図しないエラーメッセージが表示される。

> TypeError: Cannot read property 'ctor' of null
    at Function.ensureTobeComponentConstructor (http://127.0.0.1:8080/grimoire.js:8639:81)
    at GomlNode.getComponent (http://127.0.0.1:8080/grimoire.js:10807:46)
    at gr (http://127.0.0.1:8080/main.js:3:27)
    at http://127.0.0.1:8080/grimoire.js:9162:18
    at Array.forEach (native)
    at Function._onTreeInitialized (http://127.0.0.1:8080/grimoire.js:9161:43)
    at Function.addRootNode (http://127.0.0.1:8080/grimoire.js:8989:19)
    at Function._callee$ (http://127.0.0.1:8080/grimoire.js:13017:62)
    at tryCatch (http://127.0.0.1:8080/grimoire.js:7361:41)
    at Generator.invoke [as _invoke] (http://127.0.0.1:8080/grimoire.js:7652:23)

**Comment by kyasbal-1994** [comment]
おそらく、テキストで指定して、コンストラクタを取得できない場合のエラー

**Comment by moajo** [comment]
fixed.
