### ISSUE TITLE
XML parser error should report more information.

### ISSUE THREAD

**Issue by kyasbal-1994** [GrimoireGL/GrimoireJS#450]
Current error log

```
Error: Error parsing XML
    at Function.parseXML (http://localhost:8080/index.js:827:23)
    at Function._callee$ (http://localhost:8080/index.js:3150:59)
    at tryCatch (http://localhost:8080/index.js:61043:40)
    at Generator.invoke [as _invoke] (http://localhost:8080/index.js:61334:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8080/index.js:61095:21)
    at fulfilled (http://localhost:8080/index.js:3082:32)
_callee$ @ index.js:4769
tryCatch @ runtime.js:64
invoke @ runtime.js:355
prototype.(anonymous function) @ runtime.js:116
rejected @ index.js:4710
```

How can we know what is wrong?

**Comment by moajo** [comment]
fixed
