### ISSUE TITLE
The code using Grimoire.js in jsfiddle gets an error

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/GrimoireJS#471]
If you write JS code on the HTML panel it will not result in an error. 
However, if you write the code on the JS panel, it will result in an error.

https://jsfiddle.net/mp96ra1j/

```
Uncaught (in promise) Error: Unexpected error has occured during resolution of named resource 'c1'
    at NameResolver._callee$ (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:10388:39)
    at tryCatch (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:34319:40)
    at Generator.invoke [as _invoke] (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:34554:22)
    at Generator.prototype.(anonymous function) [as throw] (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:34371:21)
    at rejected (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:10273:40)
```

```
Uncaught (in promise) Error: Can not instanciate unknown geometry type custom
    at GeometryFactory._callee$ (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:9695:39)
    at tryCatch (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:34319:40)
    at Generator.invoke [as _invoke] (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:34554:22)
    at Generator.prototype.(anonymous function) [as next] (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:34371:21)
    at https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:9658:71
    at Promise (<anonymous>)
    at __awaiter (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:9638:12)
    at GeometryFactory.instanciate (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:9682:20)
    at GeometryComponent._callee$ (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:12097:48)
    at tryCatch (https://unpkg.com/grimoirejs-preset-basic@1.9.23/register/grimoire-preset-basic.js:34319:40)
```

**Comment by kyasbal-1994** [comment]
You should specify executing timing of the japascript as just after loading `<body>`. You can find that preference with clicking gear mark on javascript editor.

![image](https://cloud.githubusercontent.com/assets/6434708/25092618/7d46f11a-23c9-11e7-9f80-412c0337278f.png)

**Comment by cx20** [comment]
Thank you for your help.
